name: LoginAndRun
main: com.crazypkr.loginandrun.LoginAndRun
version: 0.1

commands:
  osenable:
    description: Commands to trigger on login permissions
    permission: loginandrun.manager
    aliases: os
    
  osdisable:
    description: Use this command to remove commands on start
    permission: loginandrun.manager
    aliases: osremove
  
  oscommands:
    description: Use this to see list of commands ran on start
    permission: loginandrun.manager
    aliases: osc

permissions:
    loginandrun.manager:
        description: LoginAndRun manager
        default: op