name: TestPlugin
main: com.crazypkr.testplugin.TestPlugin
version: 0.1

commands:
  setonstart:
    description: Use this command to run commands on start
    usage: /setonstart <command>
    permission: testplugin.manager
permissions:
    testplugin.manager:
        description: DimRestrictor managers
        default: op
    testplugin.owner:
        description: Users with this permission will bypass the restriction
        default: op