name: LogginAndRun
main: com.crazypkr.logginandrun.LogginAndRun
version: 0.1

commands:
  osenable:
    description: Commands to trigger on login permissions
    permission: logginandrun.manager
    aliases: os
    
  osdisable:
    description: Use this command to remove commands on start
    permission: logginandrun.manager
    aliases: osremove
  
  oscommands:
    description: Use this to see list of commands ran on start
    permission: logginandrun.manager
    aliases: osc

permissions:
    logginandrun.manager:
        description: LogginAndRun manager
        default: op