name: LogginAndRun
main: com.crazypkr.logginandrun.LogginAndRun
version: 0.1

commands:
  setonstart:
    description: Use this command to run commands on start
    usage: /setonstart <command>
    permission: testplugin.manager
permissions:
    logginandrun.manager:
        description: DimRestrictor managers
        default: op