name: TestPlugin
main: com.crazypkr.testplugin.TestPlugin
version: 0.1

commands:
  test:
    description: This is a demo command.
    usage: /<test>
    permission: testplugin.owner
    
permissions:
    testplugin.manager:
        description: DimRestrictor managers
        default: op
    testplugin.owner:
        description: Users with this permission will bypass the restriction
        default: op

