name: LoginAndRun
main: com.crazypkr.loginandrun.LoginAndRun
version: 1.0

commands:
  loginandrun:
    description: Main command
    aliases: lar

permissions:
    loginandrun.manager:
        description: LoginAndRun manager
        default: op